# -*- coding: utf-8 -*-
"""Day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YHh899oBYNBcf-YRPe5ejHSOkZkUeEpK
"""

# Reading input txt file
with open('/content/drive/MyDrive/day1.txt') as f:
  data = [i for i in f.read().strip().split('\n')]

calList = []
sum = 0
for i in data:
  if i == '':
    calList.append(sum)
    sum = 0
  else:
    sum += int(i)
calList.sort()
print(calList[-1])
print(calList[-1] + calList[-2] + calList[-3])

# Supposed to be print(sum(calList[-3:]))