# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CJS2R4yUSAX7XL2DNltzpTrPVx7nNRcE
"""

with open('/content/drive/MyDrive/day2.txt') as f:
  data = [i for i in f.read().strip().split('\n')]

# X = Rock, Y = Paper, Z = Scissors
# A = Rock, B = Paper, C = Scissors

winCon = ['A Y', 'B Z', 'C X']
drawCon = ['A X', 'B Y', 'C Z']
shape = {'X':1, 'Y':2, 'Z':3}

total = 0
for line in data:
  if line in winCon:
    total = total + 6 + shape.get(line[2])
  elif line in drawCon:
    total = total + 3 + shape.get(line[2])
  else:
    total = total + shape.get(line[2])
print(total)

# Part 2
# X = Lose, Y = Draw, Z = Win
# A = Rock, B = Paper, C = Scissors
winCon = ['A Z', 'B Z', 'C Z']
drawCon = ['A Y', 'B Y', 'C Y']
lossCon = ['A X', 'B X', 'C X']

total = 0 
for line in data:
  if line in winCon:
    if line[0] == 'A': # Opp Rock : Me Paper
      total += 2 + 6
    if line[0] == 'B': # Opp Paper :  Me Scissor
      total += 3 + 6
    if line[0] == 'C': # Opp Scissor : Me Rock
      total += 1 + 6
  elif line in drawCon:
    if line[0] == 'A': # Opp Rock : Me Rock
      total += 1 + 3
    if line[0] == 'B': # Opp Paper : Me Paper
      total += 2 + 3
    if line[0] == 'C': # Opp Scissor : Me Scissor
      total += 3 + 3
  else:
    if line[0] == 'A': # Opp Rock : Me Scissor
      total += 3
    if line[0] == 'B': # Opp Paper : Me Rock
      total += 1
    if line[0] == 'C': # Opp Scissor : Me Paper
      total += 2
print(total)