# -*- coding: utf-8 -*-
"""day3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bt601v4YxD-25S0Yy1RPPWKW0xX5vfTO
"""

with open('/content/drive/MyDrive/day3.txt') as f:
  data = [i for i in f.read().strip().split('\n')]

# part 1
alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
prio = {val: idx+1 for idx, val in enumerate(alphabet)}
total = 0
for string in data:
  temp1 = string[:len(string)//2]
  temp2 = string[len(string)//2:]
  for letter in temp1:
    if letter in temp2:
      total += prio[letter]
      break
print(total)

# part 2
total = 0
for string in range(0, len(data), 3):
  group = data[string:string+3]
  badge = [x for x in group[0] if x in group[1] and x in group[2]]
  for char in badge:
    total += prio[char]
    break
print(total)